News management/create
GXZheng312/project-moesland pull request #17
Opened 2023-03-26 16:24 UTC by Veaxx

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-03-27 09:25 UTC, GXZheng312 commented on backend/routes/api/newsArticle/create.js
> +var RateLimit = require('express-rate-limit');
We hebben al een request limiter middleware.

2023-03-27 09:27 UTC, GXZheng312 commented on backend/routes/api/newsArticle/create.js
> +router.post('/', upload.single('bannerImage'), async (req, res) => {
```suggestion
router.post('/', authenticateToken, upload.single('bannerImage'), async (req, res) => {
```

2023-03-27 10:05 UTC, GXZheng312 requested changes
Ik neem aan dat de moesland-app code door xander is gemaakt?

2023-03-27 10:05 UTC, GXZheng312 commented on management/src/routing.js
> +          <Route path="/" element={<Home />} />
er kunnen meerdere Route in een ProtectedRoute zitten ipv alle route zijn eigen ProtectedRoute bijvoorbeeld:
https://stackoverflow.com/questions/66289122/how-to-create-a-protected-route-with-react-router-dom

2023-03-27 20:04 UTC, Veaxx commented on backend/routes/api/newsArticle/update.js
> +router.post('/', [
Niet mijn deel

2023-03-27 20:50 UTC, Veaxx commented on management/src/routing.js
> +          <Route path="/" element={<Home />} />
Done

2023-03-27 20:56 UTC, Veaxx commented on management/src/pages/articles/create.js
> +        const imageFile = document.querySelector('input[name="image"]').files[0];
Nog niet direct gelukt. Dus laat ik staan

2023-03-28 13:28 UTC, GXZheng312 approved these changes

2023-03-28 13:36 UTC, xandermonk approved these changes

2023-03-28 13:38 UTC, merged