Login system/database
GXZheng312/project-moesland pull request #2
Opened 2023-03-10 20:35 UTC by Veaxx

# Description

Please include a summary of the change, which issue is fixed and the context if the new feature. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [X ] New feature (non-breaking change which adds functionality)

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings

2023-03-10 20:50 UTC, GXZheng312 reviewed
ik neem aan dat all nieuwe api route alleen voor testen zijn bedoelt?

2023-03-10 20:50 UTC, GXZheng312 commented on backend/models/user.js
> +  username: {
Misschien hebben we geen username nodig aangezien email ook gebruikt kan worden

2023-03-10 20:55 UTC, GXZheng312 requested changes
Kan je ook wat default data invoegen als de database leeg is? Alleen default data voor admin met admin rol

2023-03-10 22:08 UTC, xandermonk requested changes

2023-03-10 22:08 UTC, xandermonk commented on backend/routes/api/authToken/index.js
> +        res.status(200).send(`Authtoken ${token} saved successfully`);
![image](https://user-images.githubusercontent.com/56588736/224436427-5a6802f5-c72d-47a6-94fc-88abe6eefb35.png)

2023-03-10 22:08 UTC, xandermonk commented on backend/models/user.js
> +  email: {
add a lowercase option to make sure email addresses aren't case sensitive

```suggestion
  email: {
  lowercase: true,
```

2023-03-10 22:08 UTC, xandermonk commented on backend/models/user.js
> +  password: {
add a `minlength` and `maxlength`

2023-03-11 12:06 UTC, Veaxx commented on backend/models/user.js
> +  username: {
Username heb ik erin gelaten zodat je op de backend kan zien wie er is ingelogd met een naam.
Welcome Sven lijkt me wat mooier dan Welcome sn.debresser@student.avans.nl bijvoorbeeld

2023-03-11 12:07 UTC, Veaxx commented on moesland-app/README.md
> +This is a mobile app built with Expo Go. Don't forget to ``` npm ```.
Ik heb alleen in de backend folder gewerkt. Ik snap niet waarom die dit laat zien als changes lol

2023-03-11 12:23 UTC, Veaxx commented on moesland-app/README.md
> +This is a mobile app built with Expo Go. Don't forget to ``` npm ```.
Maar zal het eventjes aanpassen

2023-03-11 12:25 UTC, Veaxx commented on backend/routes/api/user/index.js
> +      password,
We hadden afgesproken om ze niet te hashen toch? Zodat Twan gemakkelijk ww terug kan kijken

2023-03-11 12:25 UTC, Veaxx commented on backend/routes/api/authToken/index.js
> +        res.status(200).send(`Authtoken ${token} saved successfully`);
Als het goed is is het nou gefixt

2023-03-11 14:05 UTC, xandermonk commented on backend/routes/api/authToken/index.js
> +        res.status(200).send(`Authtoken ${token} saved successfully`);
als je het zeker weet kun je hem handmatig weghalen

2023-03-11 14:06 UTC, Veaxx commented on backend/routes/api/authToken/index.js
> +        res.status(200).send(`Authtoken ${token} saved successfully`);
Nee ik weet het niet zeker. Heb deze error nog nooit gehad maar had een fix opgezocht en die heb ik nu toegepast haha

2023-03-11 14:07 UTC, xandermonk approved these changes

2023-03-11 14:07 UTC, xandermonk commented on backend/routes/api/user/index.js
> +      password,
Als Twan dat aan heeft gegeven kun je mijn comment negeren

2023-03-11 15:45 UTC, GXZheng312 approved these changes

2023-03-11 15:45 UTC, merged