User foto management/accept decline
GXZheng312/project-moesland pull request #26
Opened 2023-04-02 10:06 UTC by BjornVanBruchem

# Description

User images can now be managed:
- Creating
- Approving
- Declining
- Restoring
- Deleting

## Type of change

Please delete options that are not relevant and add new options if necessary. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Teststappenplan

1. Voer `npm install` en `npm run dev` uit.
2. Maak een UserImage aan via Postman met de route `/api/userImage/create`. Geef een body mee met een image (voorbeeld onderaan).
3. Test de routes `/api/userImage/approve`, `/api/userImage/decline` en `/api/userImage/restore` met als body een UserImage _id.
4. Test eventueel ook `/api/userImage/delete` met een UserImage _id.

**Voorbeeld van body voor `/create`:**
```
{
    "image": {
        "name": "TestUserImage",
        "data": "BASE64 DATA",
        "contentType": "image/jpeg"
    }
}
```
Om base64 data te krijgen, gebruik een online converter zoals [Base64 Guru](https://base64.guru/converter/encode/image).

**Voorbeeld van body voor de overige routes:**
```
{
    "id": "MongoDB _id"
}
```
Om een MongoDB _id te krijgen, kopieer 'm gewoon van de database.

2023-04-02 23:16 UTC, GXZheng312 commented on backend/routes/api/userImage/approve.js
> +router.post('/', async (req, res) => {
```suggestion
router.post('/', authenticateToken, async (req, res) => {
```

2023-04-02 23:18 UTC, GXZheng312 commented on backend/routes/api/userImage/index.js
> +router.use('/create', require('./create'));
misschien `Push` een betere beschrijvend benaming?

2023-04-02 23:20 UTC, GXZheng312 requested changes
Aan jouw route je bent authenticatie middleware vergeten (except of Create/Push)

2023-04-03 18:29 UTC, GXZheng312 requested changes

2023-04-03 18:29 UTC, GXZheng312 commented on backend/routes/api/userImage/delete.js
> +router.post('/', async (req, res) => {
hier misschien een check doen als de userImage op declined staat?

2023-04-03 18:39 UTC, FedorTselishchev approved these changes
werkt tiptop

2023-04-04 11:16 UTC, GXZheng312 approved these changes

2023-04-04 11:17 UTC, merged